<?php 

/**
 * Implementation of hook_menu.
 */
function amc12seshbro_menu() {
  $items = array();
  $items['amc2012/sessions'] = array(
    'title' => "AMC2012 Sessions",
    'page callback' => 'amc12seshbro_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Dude up a bro, sesh.
 */
function amc12seshbro_page() {
  // flag bits
  drupal_add_css(drupal_get_path('module', 'amc12seshbro') . '/css/flag.css');
  drupal_add_js(drupal_get_path('module', 'amc12seshbro') . '/flag.js');
  // our bits
  drupal_add_js(drupal_get_path('module', 'amc12seshbro')."/lib/json2.js");
  drupal_add_js(drupal_get_path('module', 'amc12seshbro')."/lib/backbone.js");
  drupal_add_js(drupal_get_path('module', 'amc12seshbro')."/lib/doT/doT.min.js");
  drupal_add_js(drupal_get_path('module', 'amc12seshbro')."/lib/jquery.styleform.js");
  drupal_add_js(drupal_get_path('module', 'amc12seshbro')."/amc12seshbro.js");
  drupal_add_css(drupal_get_path('module', 'amc12seshbro')."/css/styleform.css");
  drupal_add_css(drupal_get_path('module', 'amc12seshbro')."/css/amc12seshbro.css");

  drupal_set_html_head(file_get_contents(drupal_get_path('module', 'amc12seshbro')."/amc12seshbro.jst.html"));

  //$bkmkblk = views_embed_view('bkmkd_seshes', 'block_1');

  $output = "<div id=\"amc12seshbro\" class=\"session-browser-wait\">Loading sessions...</div>";
  //$output .= "<div id=\"amc12seshbro-bkmks\">";
  //$output .= $bkmkblk;
  //$output .= "</div>";

  return $output;
}
