<?php 

/**
 * Implementation of hook_menu.
 */
function amc12seshbro_menu() {
  $items = array();
  $items['amc2012/sessions'] = array(
    'title' => "Conference Schedule",
    'page callback' => 'amc12seshbro_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Dude up a bro, sesh.
 */
function amc12seshbro_page() {

  drupal_add_js(drupal_get_path('module', 'amc12seshbro')."/amc12seshbro.js");
  drupal_add_css(drupal_get_path('module', 'amc12seshbro')."/amc12seshbro.css");

  return "<div id=\"amc12seshbro\" class=\"session-browser-wait\"></div><a href='http://talk.alliedmedia.org/sessions/list'>View a flat, screen reader-friendly list of all AMC sessions here.</a>";
}
