<?php 

/**
 * Implementation of hook_menu.
 */
function amc13seshbro_menu() {
  $items = array();
  $items['amc2013/sessions'] = array(
    'title' => "AMC2013 Sessions",
    'page callback' => 'amc13seshbro_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Dude up a bro, sesh.
 */
function amc13seshbro_page() {
  // flag bits
  drupal_add_css(drupal_get_path('module', 'amc13seshbro') . '/css/flag.css');
  drupal_add_js(drupal_get_path('module', 'amc13seshbro') . '/flag.js', 'footer');
  // our bits
  drupal_add_js(drupal_get_path('module', 'amc13seshbro')."/lib/json2.js", 'footer');
  drupal_add_js(drupal_get_path('module', 'amc13seshbro')."/lib/backbone.js", 'footer');
  drupal_add_js(drupal_get_path('module', 'amc13seshbro')."/lib/doT/doT.min.js", 'footer');
  drupal_add_js(drupal_get_path('module', 'amc13seshbro')."/lib/jquery.styleform.js", 'footer');
  drupal_add_js(drupal_get_path('module', 'amc13seshbro')."/amc13seshbro.js", 'footer');
  drupal_add_css(drupal_get_path('module', 'amc13seshbro')."/css/styleform.css");
  drupal_add_css(drupal_get_path('module', 'amc13seshbro')."/css/amc13seshbro.css");

  drupal_set_html_head(file_get_contents(drupal_get_path('module', 'amc13seshbro')."/amc13seshbro.jst.html"));

  //$bkmkblk = views_embed_view('bkmkd_seshes', 'block_1');

  $output = "<div id=\"amc13seshbro\" class=\"session-browser-wait\">Loading sessions...</div>";
  //$output .= "<div id=\"amc13seshbro-bkmks\">";
  //$output .= $bkmkblk;
  //$output .= "</div>";

  return $output;
}
